debug_lidar_viz: true
camera_optical_frame: "walrus/realsense_front_color_optical_frame"
robot_frame: "walrus/base_link"
map_frame: "walrus/map"
distance_threshold: 0.2
confidence_threshold: 1.0
distance_between_targets: 10.0
bbox_pixel_padding: 0
object_classes: 
  person: '1'
